language: python
sudo: required

install: "sudo apt-get update && sudo apt-get install -y libgeoip-dev python-dev && pip install --upgrade pip && pip install tox"

# just listing everything in the matrix, because:
# - anything else apparently failed
# - this is what klein does

matrix:
  include:
# these two are "special", we only run them in "a really new python"
  - python: "3.6"
    env: TOX_ENV=flake8
  - python: "3.6"
    env: TOX_ENV=readme_render

# python 3.6

  - python: "3.6"
    env: TOX_ENV=py36-tx16
  - python: "3.6"
    env: TOX_ENV=py36-tx17
  - python: "3.6"
    env: TOX_ENV=py36-tx18
  - python: "3.6"
    env: TOX_ENV=py36-tx19
  - python: "3.6"
    env: TOX_ENV=py36-tx20

# python 3.7

  - python: "3.7"
    env: TOX_ENV=py37-tx20

# python 3.8

  - python: "3.8"
    env: TOX_ENV=py38-tx20

# python 2.7

  - python: "2.7"
    env: TOX_ENV=py27-tx16
  - python: "2.7"
    env: TOX_ENV=py27-tx17
  - python: "2.7"
    env: TOX_ENV=py27-tx18
  - python: "2.7"
    env: TOX_ENV=py27-tx19
  - python: "2.7"
    env: TOX_ENV=py27-tx20

# PyPy

  - python: "pypy"
    env: TOX_ENV=pypy-tx16
  - python: "pypy"
    env: TOX_ENV=pypy-tx17
  - python: "pypy"
    env: TOX_ENV=pypy-tx18
  - python: "pypy"
    env: TOX_ENV=pypy-tx19
  - python: "pypy"
    env: TOX_ENV=pypy-tx20

script:
  - apt-cache policy libssl-dev
  - tox -c tox.ini -e $TOX_ENV

after_success:
  - coveralls
  - codecov
